### ISSUE TITLE
Add Means to Buy/Build Boats

### ISSUE THREAD

**Issue by erinmaus** [erinmaus/itsyscape#18]
# Acceptance Criteria
* Can buy a basic boat
* Player can only own one boat at a time

**Comment by aaronbolyard** [comment]
Working on Portmaster NPC.

* Will be able to buy & name a ship
* Can customize ship after being bought (sails, helm, cannons, rigging, figurehead, color, storage)
* Customization costs money & supplies

The first ship costs 200 common logs, 100 cotton, 50 iron bars, and 100,000 gold.

* Iron cannons (1 sailing) and wrought iron cannon (20 sailing) are only cannons available
* Basic figurehead (same colors as basic shirts), jeweled figurehead (requires gems), golden figurehead (expensive), demon figurehead (requires bone shards, expensive)
* Color customization costs money, only aesthetic
* Storage: crate (25 slots), common chest (50 slots)
* Rigging: Cotton rigging, reinforced cotton rigging
* Helm: Squeaky helm, croaking helm
* Sails: same colors as basic shirts; Jolly Roger is a piracy feature

* Show a cute illustration of the ship for a preview.
* Show ship stats (distance, speed, health, offense, storage).

Piracy is a separate feature. Requires a Jolly Roger-class sail.
