### ISSUE TITLE
Launcher did not install game on Windows

### ISSUE THREAD

**Issue by gitPARacct** [erinmaus/itsyscape#26]
Error

boot.lua:481: Cannot load game at path 'C:/Users/*********'.
Make sure a folder exists at the specified path.

Traceback

[C]: in function 'error'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by erinmaus** [comment]
Can you post the contents of %APPDATA%\ItsyRealmLauncher\launcher\manifest.ini?

In the folder %APPDATA%\ItsyRealmLauncher\launcher, is there a 'Game.zip' folder?

**Comment by gitPARacct** [comment]
contents of manifest: version = 0.2.12-alpha

There is not a game.zip folder

There is a %APPDATA%\ItsyRealmLauncher\game folder.  Contents

![image](https://user-images.githubusercontent.com/71905433/95140988-0ea51a00-073e-11eb-8d04-f2dc5cd30b58.png)

It doesn't appear to uninstall in the windows uninstaller, and it won't just let me delete the folders referenced above

**Comment by erinmaus** [comment]
Is the censored path:

`C:\Users\<USERNAME>\AppData\Roaming\ItsyRealmLauncher\game\itsyrealm.love`? Or is it something else?

**Comment by gitPARacct** [comment]
Tried to delete and reinstall, this time I received the same error again.  The full path is: C:\Users\<username>\AppData\Roaming\ItsyRealmLauncher\game

**Comment by erinmaus** [comment]
Oh! So there is no `itsyrealm.love` at the end?

**Comment by gitPARacct** [comment]
This is fixed!
